In [5]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

In [6]:
dataset = pd.read_csv("data.csv")

In [7]:
dataset

Age          Workclass  Fnlwgt    Education  Education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            Marital_status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           Sex  Capital_gain  Capital_loss  Hours_per_week  Native_country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       Salary  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [8]:
dataset = dataset.apply(LabelEncoder().fit_transform)

In [10]:
dataset

Age  Workclass  Fnlwgt  Education  Education_num  Marital_status  \
0       22          7    2671          9             12               4   
1       33          6    2926          9             12               2   
2       21          4   14086         11              8               0   
3       36          4   15336          1              6               2   
4       11          4   19355          9             12               2   
...    ...        ...     ...        ...            ...             ...   
32556   10          4   16528          7             11               2   
32557   23          4    8080         11              8               2   
32558   41          4    7883         11              8               6   
32559    5          4   12881         11              8               4   
32560   35          5   17825         11              8               2   

       Occupation  Relationship  Race  Sex  Capital_gain  Capital_loss  \
0               1             1     4    1            25             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0           108             0   

       Hours_per_week  Native_country  Salary  
0                  39              39       0  
1                  12              39       0  
2                  39              39       0  
3                  39              39       0  
4                  39               5       0  
...               ...             ...     ...  
32556              37              39       0  
32557              39              39       1  
32558              39              39       0  
32559              19              39       0  
32560              39              39       1  

[32561 rows x 15 columns]

In [11]:
x=dataset.drop(['Salary'],axis=1)

In [12]:
x

Age  Workclass  Fnlwgt  Education  Education_num  Marital_status  \
0       22          7    2671          9             12               4   
1       33          6    2926          9             12               2   
2       21          4   14086         11              8               0   
3       36          4   15336          1              6               2   
4       11          4   19355          9             12               2   
...    ...        ...     ...        ...            ...             ...   
32556   10          4   16528          7             11               2   
32557   23          4    8080         11              8               2   
32558   41          4    7883         11              8               6   
32559    5          4   12881         11              8               4   
32560   35          5   17825         11              8               2   

       Occupation  Relationship  Race  Sex  Capital_gain  Capital_loss  \
0               1             1     4    1            25             0   
1               4             0     4    1             0             0   
2               6             1     4    1             0             0   
3               6             0     2    1             0             0   
4              10             5     2    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32556          13             5     4    0             0             0   
32557           7             0     4    1             0             0   
32558           1             4     4    0             0             0   
32559           1             3     4    1             0             0   
32560           4             5     4    0           108             0   

       Hours_per_week  Native_country  
0                  39              39  
1                  12              39  
2                  39              39  
3                  39              39  
4                  39               5  
...               ...             ...  
32556              37              39  
32557              39              39  
32558              39              39  
32559              19              39  
32560              39              39  

[32561 rows x 14 columns]

In [13]:
y=dataset.Salary

In [14]:
y

0        0
1        0
2        0
3        0
4        0
        ..
32556    0
32557    1
32558    0
32559    0
32560    1
Name: Salary, Length: 32561, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.10)

In [22]:
from sklearn.tree import DecisionTreeClassifier  
dtree = DecisionTreeClassifier()

In [23]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [24]:
print(X_test)
predictions = dtree.predict(X_test)
predictions

       Age  Workclass  Fnlwgt  Education  Education_num  Marital_status  \
26176    8          7   18098         15              9               4   
11976   13          4    6317          9             12               2   
32307   25          5   11774          9             12               2   
22283   42          4   10070         15              9               5   
3984    32          4    2300          6              4               0   
...    ...        ...     ...        ...            ...             ...   
13574   15          4    2924         15              9               2   
24233   11          4     450         11              8               2   
8847    10          0   17953          9             12               2   
17473   22          4   11407         15              9               0   
8364    26          0    7136         11              8               0   

       Occupation  Relationship  Race  Sex  Capital_gain  Capital_loss  \
26176           3        

array([0, 1, 1, ..., 0, 0, 0])

In [25]:
from sklearn.metrics import classification_report,confusion_matrix

In [26]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.88      0.87      0.87      2485
           1       0.59      0.62      0.60       772

    accuracy                           0.81      3257
   macro avg       0.73      0.74      0.74      3257
weighted avg       0.81      0.81      0.81      3257



In [27]:
print(confusion_matrix(y_test,predictions))

[[2151  334]
 [ 295  477]]


In [33]:
X_in = np.array([22,7,2671,9,12,4,1,1,4,1,25,0,39,39])

In [34]:
y_pred =dtree.predict([X_in])

/home/nithin/Desktop/foss/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [35]:
y_pred

array([0])

In [36]:
#Saving the Model
import pickle
pickle_file= open("sdecision_tree.pkl", "wb") 
pickle.dump(dtree, pickle_file) 
pickle_file.close()